name = "aiken-lang/offchain-example"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/offchain-example'"

[repository]
user = "aiken-lang"
project = "offchain-example"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "modulo-p/ak-381"
version = "v0.1"
source = "github"

[config]
